call pathogen#incubate()
call pathogen#helptags()

"autocmd FileType html,htmldjango,jinjahtml,eruby,mako
"let b:closetag_html_style=1
"autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako 
"source ~/.vim/bundle/closetag/plugin/closetag.vim

set tabstop=2
set sw=2
"set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
"set list
set nu
"Solarized 
set t_Co=256
syntax on
set background=dark
"let g:solarized_termtrans=1
"let g:solarized_termcolors=256
"let g:solarized_contrast="high"
"let g:solarized_visibility="high"
colorscheme solarized


set encoding=utf-8 "Encoding displayed
set fileencoding=utf-8 " The encoding written to file
