#Only called on login - with the exception of mac which runs bashrc
#Put path changes in bash_path
#Put aliases in bash_alias
#Everything else in bashrc

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
