#Only called on login - with the exception of mac which runs bashrc
#Put path changes in bash_path
#Put aliases in bash_alias
#Everything else in bashrc

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi


# added by Anaconda 2.1.0 installer
export PATH="//anaconda/bin:$PATH"

# added by Anaconda 2.1.0 installer
export PATH="/Users/timckag/anaconda/bin:$PATH"
