export PATH="/usr/local/mysql/bin:$PATH"
#export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH
export JAVA_HOME=/Library/Java/Home
export CATALINA_HOME=/Library/Tomcat
export PATH=${PATH}:/Users/timmckague/bin

##
# Your previous /Users/timmckague/.bash_profile file was backed up as /Users/timmckague/.bash_profile.macports-saved_2013-08-30_at_09:37:25
##


export PATH="/usr/local/bin:$ANT_HOME/bin:"$PATH


if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
